spring.application.name=notification-service

server.port=8082

SAGA_QUEUE_VALUE=notification:events

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379

AWS_REGION=eu-north-1
AWS_SNS_TOPIC_ARN=${AWS_SNS_TOPIC_ARN}




